### ISSUE TITLE
 Add license request

### ISSUE THREAD

**Issue by Tisks** [YahyaOdeh/HealthWatcher#13]
I'm interested in cloning and modifying your android app code in order to advance in my undergraduate thesis.

This app will be used just to get the final data of the health measurements and turn it into another format to be posted on a database (the actual local sql lite's data wont be stored externally) . It wont be used commercially in the future (the actual software I'm working on is in it's early development stage and possibly will be open source), its just an example data source for the software.

I cannot use this repo without a license since according to https://help.github.com/articles/licensing-a-repository/ it is effectively cannot be used without your written permission.

An open source license would suit my needs at the moment.

I provide you with a summary of the open licenses here : 
https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633#file-open_source_licenses-md

I hope I can use your code fairly because helps my cause grandly.

**Comment by YahyaOdeh** [comment]
Hello Tiks,

I’m so glad to receive your request and I’ve updated the licenses you can check it out. Hope it suits you and if it doesn’t just re-email me.

Best of luck and stay safe :D

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: ***@***.***>
Sent: Thursday, March 11, 2021 11:01 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [YahyaOdeh/HealthWatcher] Add license request (#13)


I'm interested in cloning and modifying your android app code in order to advance in my undergraduate thesis.

This app will be used just to get the final data of the health measurements and turn it into another format to be posted on a database (the actual local sql lite's data wont be stored externally) . It wont be used commercially in the future (the actual software I'm working on is in it's early development stage and possibly will be open source), its just an example data source for the software.

I cannot use this repo without a license since according to https://help.github.com/articles/licensing-a-repository/ it is effectively cannot be used without your written permission.

An open source license would suit my needs at the moment.

I provide you with a summary of the open licenses here :
https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633#file-open_source_licenses-md

I hope I can use your code fairly because helps my cause grandly.

**Comment by Tisks** [comment]
Thanks! it addresses all my needs :)

Stay save and good luck in general :D
